### ISSUE TITLE
Morning Peer to Peer Code Review 26/01/2023

### ISSUE THREAD

**Issue by sunga12** [Matthieu96Code/portfolio-setup-mobile-first#11]
1. Add full path to image urls. i.e. Start image source path with "./
2. Suggestion to change Lines 70 - 76 in css file, rather use (**transform: rotate()**) directly instead of using keyframes
3. Add labels to contact form to meet accessibility requirements
4. Minor change to About section to Add Skills Text instead of Frameworks twice

Very good Responsive Web Design, code looks clean and professionally written.

**Comment by Matthieu96Code** [comment]
Follow all the requirements in this code review 
closes #18
